# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types: ["closed"]
    branches: [ "main", "build" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  name: Johnny
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      name: John D.
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, $name!

  pull_request_only:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Access the special "github" object to get information about the environment
    if: github.event_name == 'pull_request'

    # Specify the job has to run after the "build" job has run
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Hello, $name!
